[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = PhilippinoOrCorean
admin_passwd = $pbkdf2-sha512$600000$GAOAkPJ.b03p3bu3tvZe6w$.SkQB/I8g8w3taYiMmFAHySxJD8o8wUK9C9ram8isE8s1CDqA9l5TUSQFNl68N6fnve3QcdDlQtI.zVx25w.lw
